### ISSUE TITLE
"No streams found" - again - 6.8.15

### ISSUE THREAD

**Issue by macruspareto** [anxdpanic/plugin.video.youtube#168]

**Comment by u19809** [comment]
Yes I have the problem too

**Comment by Nigel1992** [comment]
I'm having this problem too.

Update: Fixed by simply restarting my AsusWRT Merlin Router

**Comment by edenist** [comment]
Confirming I've been getting this error for about since early July as well. 
No restart/setting/network environment fixes have been found for me yet, which suggests google changed something on their end?

**Comment by whisperdancer** [comment]
Was working fine, just today getting same error "No Streams Found" dialog pops up when trying to play any video. I linked device as per instructions hoping that would fix it. Rebooted kodi didn't work. Error persists on every video now.

**Comment by Jamesuperfun** [comment]
Also having this issue on 6.8.17

**Comment by edenist** [comment]
This is still happening for me on 6.8.17, though it is only one some channels. I still haven't worked out what is special about their videos yet. 

An example of a channel which throws this error is https://www.youtube.com/c/classicwilty

**Comment by edenist** [comment]
I don't know if this issue was fixed intentionally with 6.8.18 or not, but now that I try to play videos from the above channel, the video still fails but I receive the notification "This video is not available in your country", which though frustrating makes sense why I cannot play it!

I guess the plugin has now been updated to capture and report this error now!

**Comment by posliedov** [comment]
6.8.18
the problem is still here…
debug log – https://pastebin.com/YD6DcnSY
