### ISSUE TITLE
'My Subscriptions' fails to load and causes error in 6.8.24

### ISSUE THREAD

**Issue by reven** [anxdpanic/plugin.video.youtube#392]
Still have the same issue (see #368). Same steps to reproduce and same error messages in logs.

'My suscriptions' fails to load with sometimes timing out and causing a plugin crash, and other times just loading the videos of one channel at random. Login and auth is correct, as other videos play properly (when visiting suscriptions > channel, for example) and searches or watched status has no issues.

The log just shows the same error again and again. Side issue is that log file must be purged periodically because it gets really big.

This happens on Kodi 19.4.0 and Ubuntu 22.04.1

This is the error log (fresh capture today with 6.8.24): 
[youtube.plugin.error.log.zip](https://github.com/anxdpanic/plugin.video.youtube/files/10421729/youtube.plugin.error.log.zip)

**Comment by malversoft** [comment]
I started to suffer the #368 bug yesterday, 4 feb 2023, for no apparent reason. No changes were made in my Kodi setup. Kodi just started to hang whenever I try to enter in the ”My subscriptions” option of the Youtube plugin.

It is a true pity, because ”My subscriptions” list of Youtube videos is probably the feature I use most in Kodi. Now unusable.

Kodi version: 20.0 (Nexus)
Youtube addon: 6.8.24
Using Youtube API key.

**Comment by malversoft** [comment]
An update on this.

At least in my case, it seems that the presence of specific videos in the list (any list) is what makes Kodi hang.

The offending video under "My subscriptions" is now on the second page of the list. So now I can list the first page of "My subscriptions", and Kodi hangs when I try to list the second page.

Other videos lists are also crahsing ("Popular right now", specific searches...). My guess is that some characteristic, value or special character makes the entire list hang when it is present in a video.

Unfortunately I cannot determine which videos make Kodi hang when listed, because it hangs and I cannot even see the list.

I hope the logs are informative enough for the deveolper. I have attached three logs of the instant when Kodi hangs:
- One for the (now second page of) "My subscriptions" list.
- One for "Popular right now" list.
- One for the results of a search of the term "biyin".

In all the logs these lines can be seen repeated tens of times:
```
2023-02-09 22:57:33.574 T:87668 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-02-09 22:57:33.574 T:87668 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
```

Thanks in advance for your help.

[20230209.Kodi.logs.zip](https://github.com/anxdpanic/plugin.video.youtube/files/10702102/20230209.Kodi.logs.zip)

**Comment by anxdpanic** [comment]
totally different issues, than the one linked. this is usually a connection issue on YouTube's end. Nothing I can do, it resolves itself.

@malversoft that log spam is unrelated and is fixed in the latest alpha

**Comment by malversoft** [comment]
What an incredibly fast response. Thanks for your dedication, man!

> this is usually a connection issue on YouTube's end. Nothing I can do, it resolves itself.

Do you  mean my issue or the one linked in the first message? (You said they are unrelated)
Which one are you describing?

If the warnings seen in my logs are unrelated to my issue, then the entire thing is hanging without even a clue in the log. Is that correct?

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/plugin.video.youtube/issues/368 is not the same as this issue (the one the others referenced)
and the log spam isn't the issue, that will just make some labels incorrect/incomplete.
That can be fixed with https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev

As for the hanging being a specific video, i'd need that log. as the first log in this issue shows a connection issue.

**Comment by malversoft** [comment]
> As for the hanging being a specific video, i'd need that log. as the first log in this issue shows a connection issue.

I already attached three logs of the crash, describing the three crash cases. Altough the warnings spam is not related, those were the logs of my issue.

Just tried 6.8.25.alpha. Still crashing. Logs are exactly the same but without the ”warning (general)” lines.

**Comment by malversoft** [comment]
My final update on this.

I have found two specific videos that provoke the issue and make my Kodi crash.
https://www.youtube.com/watch?v=QfnmAMR_pn8
https://www.youtube.com/watch?v=H5Bmx3HVKaU
(they both have an emoji in the title, maybe that has something to do with the issue)

I made some testing and here is what I got:

1. If I make one of the offending Youtube videos to be included in any video list of the Youtube plugin (by subcribing, searching, etc.), Kodi crashes before showing the list.
If no offending videos are listed, everything works ok.
No crashes are observed either in the videos listings of other plugins.

2. If I send an offending video to the Youtube plugin via Yatse (I think it just sends the link to Kodi via LAN), the offending video plays without problem.

And then came the strangest part:

3. If I send an offending video to Youtube plugin via Yatse **while ANY video list is shown in any Kodi plugin**, the list freezes and Kodi hangs.
As a negative check ,if I send any non-offendnig video to Youtube plugin via Yatse while a video list is shown, the video plays normally.

These tests can be reproduced anytime with the same results.

As the 3rd test points to the listing of videos in Kodi as the one to blame, I did a last test changing my Kodi skin, from Confluence to Estuary, and...
... voilà, the crashes disappeared.

So it seems that the issue is related to specific Youtube videos AND the listing of videos in the Confluence skin. Not related to the Youtube plugin.

I really do not like Estuary skin and prefer to stick with the old default Confluence. But I really do not know how to start explaining all this to the Confluence skin maintainers (if there is any).

**Comment by MaxmaxOk** [comment]
Hi i have the same problem...using Estuary skin makes the problem disappear,when i use other skins the problem appear again! I hope this could ever been resolved but how???

**Comment by fernandolordan** [comment]
I have also tested other Confluence-alike or Confluence-derived skins, and all them suffer the crash with the ”offending” videos (presumably videos with non-standard characters in their titles).

Estuary skin has that corrected. So Confluence developers should apply the same correction to the Confluence skin.

Definitely it seems not a problem of the Youtube plugin.

**Comment by malversoft** [comment]
I have also tested other Confluence-alike or Confluence-derived skins, and all them suffer the crash with the ”offending” videos (presumably videos with non-standard characters in their titles).

Estuary skin has that corrected. So Confluence developers should apply the same correction to the Confluence skin.

Definitely it seems not a problem of the Youtube plugin.

**Comment by MaxmaxOk** [comment]
Is strange that the problem starts some month ago...before that, other skins worked fine without this problem...seems like youtube videos titles with emoji icons makes kodi crash....should be upgrading kodi from 19.5 to 20?

**Comment by reven** [comment]
@MaxmaxOk This is not the same issue that I was describing. It seems it is the same than the one @malversoft was referencing, which depends on the theme.

Just to be clear, the issue I opened the issue for is that "My Subscriptions" fails to load or loads channels at random. However, all the videos can be seen by checking each individual channel by going to `subscriptions > channel`

@anxdpanic, is there anything else I can provide to help trouble-shoot the issue? Do you have any idea of what I could try to fix it?

**Comment by malversoft** [comment]
@reven , sorry for having mixed here my issue, which in the end seems not related to yours. The confusion came from the fact that the first symptom I detected was similar.

@MaxmaxOk , updating Kodi to 20.0 does not fix the emoji crash in Confluence-derived skins. Tested.

**Comment by kuraikaze** [comment]
The font/character/emoji issue that has been a widespread problem with many skins & addons seems to be resolved here: https://github.com/xbmc/xbmc/pull/22658

Just waiting for the next Kodi point release to go live so I can test against the skins/plugins I use

**Comment by MO35AB** [comment]
I think i have the same issue here, when opening my subscriptions kodi crashes, i changed the theme from eminance 2 to Estuary, i can see some squares on some videos, it works now, i think its arabic letters.
