### ISSUE TITLE
Error 403 suddenly without reason

### ISSUE THREAD

**Issue by bonome54** [anxdpanic/plugin.video.youtube#509]
### Context

Since a week, the add-on refuse to work. I've been getting a 403 error when I try to play a video on Youtube. I haven't touched anything, the api configuration was correct. I've tried redoing the api configuration but it's the same result.

### Log

2023-08-19 14:59:17.685 T:1000     info <general>: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=e2mIDhr5ERw
2023-08-19 14:59:17.686 T:9051     info <general>: Creating InputStream
2023-08-19 14:59:17.802 T:9051    error <general>: CCurlFile::CReadState::FillBuffer - (0x7fba0c3cea70) Failed: HTTP returned code 403
2023-08-19 14:59:17.803 T:9051    error <general>: CCurlFile::Open - <https://rr8---sn-4gxx-hgns.googlevideo.com/videoplayback?expire=1692471557&ei=pbzgZL_cIqyCp-oPpdu4kAk&ip=82.66.78.137&id=o-APh1gqAUjBRuvvZm21iLtgFfcwOjNhPzJjLt7d2IcTJe&itag=22&source=youtube&requiressl=yes&mh=OV&mm=31%2C29&mn=sn-4gxx-hgns%2Csn-25glenes&ms=au%2Crdu&mv=m&mvi=8&pl=22&initcwndbps=1706250&siu=1&spc=UWF9f0mynIzYxEQ3OVb-rfxYqjekP10OJv9yDRoKUTcGl_fHXtviuFE&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=1310.325&lmt=1692091712982558&mt=1692449587&fvip=2&fexp=24007246%2C51000023&beids=24350017&c=ANDROID&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Csiu%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgQ4DRWa5CvrvnOJ0Aef2ilGxERFCjxJM5OrUdFE-l8vsCIHpFzO6eml2qAmAM4ALQ3c7qTIR9viir6KfMvOCplGLN&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhANdZThgBHSosr-rPcBaiRCshydKwsGYsYybo_dN1JtDzAiEA03ZdoSDwqLlh1x8dTA1VqcAH0nsRrU41BOiJ1BriKAA%3D&range=0-> Failed with code 403:
                                                   
2023-08-19 14:59:17.803 T:9051    error <general>: CFileCache::Open - <https://rr8---sn-4gxx-hgns.googlevideo.com/videoplayback?expire=1692471557&ei=pbzgZL_cIqyCp-oPpdu4kAk&ip=82.66.78.137&id=o-APh1gqAUjBRuvvZm21iLtgFfcwOjNhPzJjLt7d2IcTJe&itag=22&source=youtube&requiressl=yes&mh=OV&mm=31%2C29&mn=sn-4gxx-hgns%2Csn-25glenes&ms=au%2Crdu&mv=m&mvi=8&pl=22&initcwndbps=1706250&siu=1&spc=UWF9f0mynIzYxEQ3OVb-rfxYqjekP10OJv9yDRoKUTcGl_fHXtviuFE&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=1310.325&lmt=1692091712982558&mt=1692449587&fvip=2&fexp=24007246%2C51000023&beids=24350017&c=ANDROID&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Csiu%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgQ4DRWa5CvrvnOJ0Aef2ilGxERFCjxJM5OrUdFE-l8vsCIHpFzO6eml2qAmAM4ALQ3c7qTIR9viir6KfMvOCplGLN&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhANdZThgBHSosr-rPcBaiRCshydKwsGYsYybo_dN1JtDzAiEA03ZdoSDwqLlh1x8dTA1VqcAH0nsRrU41BOiJ1BriKAA%3D&range=0-> failed to open
2023-08-19 14:59:17.803 T:9051    error <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.youtube/play/?video_id=e2mIDhr5ERw]
2023-08-19 14:59:17.803 T:9051     info <general>: CVideoPlayer::OnExit()
2023-08-19 14:59:17.813 T:1000     info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2023-08-19 14:59:17.816 T:1000     info <general>: CVideoPlayer::CloseFile()
2023-08-19 14:59:17.816 T:1000     info <general>: VideoPlayer: waiting for threads to exit
2023-08-19 14:59:17.816 T:1000     info <general>: VideoPlayer: finished waiting
2023-08-19 14:59:17.820 T:9001    error <general>: GetDirectory - Error getting -

Please provide any relevant information about your setup

* Add-on Version: v7.0.2~alpha7
* Kodi Version: 20.2.0
* Kodi GUI Language: French
* Operating System: LibreELEC (official): 11.0.3 (Generic.x86_64) 
* Operating System Language: English

**Comment by MoojMidge** [comment]
Duplicate of https://github.com/anxdpanic/plugin.video.youtube/issues/501

**Comment by MoojMidge** [comment]
Should be fixed in this [test version](https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip) which you can use until a new release is made.

**Comment by bonome54** [comment]
As you suggested @MoojMidge, I tried the last version with the api configuration that used to work and the new one, both crashed with the same 403 error. I looked into the google console, there is no error on this side.
![image](https://github.com/anxdpanic/plugin.video.youtube/assets/23456154/1b1bb6bc-aa0b-4c5f-aaf6-f73086022f86)

Still don't know what to do...

**Comment by MoojMidge** [comment]
Can you provide a full debug log using the test version?

There is no need to change the API keys.

**Comment by bonome54** [comment]
Here it is. I hope there is everything you need, I was not sure how to enable debug logging.
[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/12437530/kodi.log)

**Comment by bonome54** [comment]
I removed and reinstalled the extension from the beginning. I didn't even take the latest version, I just took the one in the official repository. I redid all the configuration and tadah it works! So I'm closing this issue, but I still don't know what happened.
