### ISSUE TITLE
Finished live streams won't play

### ISSUE THREAD

**Issue by AlexNk** [anxdpanic/plugin.video.youtube#579]
* Add-on Version: 7.0.3 - beta3 and older
* Kodi Version: LibreELEC 11.0.6

Regular videos and active live streams play fine, but some of the finished live streams won't play.
Example: https://www.youtube.com/watch?v=2aAkIxrJN3s

"Use alternative player" and "Use YouTube website URLs" are disabled.
InputStream Helper is installed

I tried searching the issues and updating/re-installing the addons, but nothing works.

Logs:
```
2024-02-11 14:09:34.719 T:990      info <general>: [plugin.video.youtube] Running: YouTube (7.0.3+beta.3+unofficial.1) on Nexus (Kodi-20.3) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': '2aAkIxrJN3s'}
2024-02-11 14:09:35.312 T:752      info <general>: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=2aAkIxrJN3s
2024-02-11 14:09:35.313 T:2587     info <general>: Creating InputStream
2024-02-11 14:09:35.314 T:2587     info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 0
2024-02-11 14:09:35.316 T:2587    error <general>: CCurlFile::Open - <http://127.0.0.1:50152/youtube/manifest/dash/2aAkIxrJN3s.mpd/mpd_version/5> Failed with code 404:
                                                   
2024-02-11 14:09:35.316 T:2587    error <general>: AddOnLog: inputstream.adaptive: CURLOpen returned an error, download failed: http://127.0.0.1:50152/youtube/manifest/dash/2aAkIxrJN3s.mpd/mpd_version/5
2024-02-11 14:09:35.316 T:2587    error <general>: AddOnLog: inputstream.adaptive: Could not open / parse manifest (http://127.0.0.1:50152/youtube/manifest/dash/2aAkIxrJN3s.mpd/mpd_version/5)
2024-02-11 14:09:35.316 T:2587    error <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.youtube/play/?video_id=2aAkIxrJN3s]
2024-02-11 14:09:35.316 T:2587     info <general>: CVideoPlayer::OnExit()
2024-02-11 14:09:35.316 T:2587     info <general>: ADDON: Dll Destroyed - InputStream Adaptive
2024-02-11 14:09:35.428 T:752      info <general>: CVideoPlayer::CloseFile()

```

**Comment by MoojMidge** [comment]
Hmm that's odd. There was a previous issue where completed live streams were indicating they were live even when they weren't, and there were no live stream manifests urls available to use. 

In this issue it seems that the stream is still indicating it is live when it isn't, and that there is a manifest url present, but it is empty. Easy enough to fix, but I think the real issue is that this is a `isPostLiveDvr` video stream, i.e. caught in the middle of processing, but the original live video stream is no longer available to use.

Where you able to view the video on the website at the same time that it didn't work in the plugin?

**Comment by AlexNk** [comment]
> Where you able to view the video on the website at the same time that it didn't work in the plugin?

Yes. All of such videos play fine in Web Browser, and Android app. And they are still in my Subscriptions or can be found by search.

**Comment by MoojMidge** [comment]
This is normally only a temporary issue, but to be clear, when you say the following:

> Yes. All of such videos play fine in Web Browser, and Android app. And they are still in my Subscriptions or can be found by search.

Does the problem eventually resolve itself, or do these videos never work?

Anyway should be fixed by https://github.com/MoojMidge/plugin.video.youtube/commit/50fa66bef46b1a347751cd2fedd246792c11f1d9

**Comment by AlexNk** [comment]
> Does the problem eventually resolve itself, or do these videos never work?

It seems that it solves in about a week. I checked with several videos that didn't play before, and those that were issued more than 6-7 days ago are playing fine now.

> Anyway should be fixed by [MoojMidge@50fa66b](https://github.com/MoojMidge/plugin.video.youtube/commit/50fa66bef46b1a347751cd2fedd246792c11f1d9)

I used this commit with 7.0.3 beta3 and the videos still won't play, but the logs look different now:

```
2024-02-12 11:06:46.170 T:754      info <general>: VideoPlayer::OpenFile: https://www.youtube.com/live/2aAkIxrJN3s?si=7UPfdhyLCTfEryuL
2024-02-12 11:06:46.976 T:813      info <general>: Creating InputStream
2024-02-12 11:06:47.246 T:813      info <general>: Creating Demuxer
2024-02-12 11:06:47.665 T:791      info <general>: PVR Manager: Starting cleanup of cached images.
2024-02-12 11:06:48.180 T:813     error <general>: Open - error probing input format, https://www.youtube.com/live/2aAkIxrJN3s?si=7UPfdhyLCTfEryuL
2024-02-12 11:06:48.180 T:813     error <general>: OpenDemuxStream - Error creating demuxer
2024-02-12 11:06:48.180 T:813      info <general>: CVideoPlayer::OnExit()
2024-02-12 11:06:48.195 T:754      info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2024-02-12 11:06:48.200 T:754      info <general>: CVideoPlayer::CloseFile()
2024-02-12 11:06:48.200 T:754      info <general>: VideoPlayer: waiting for threads to exit
2024-02-12 11:06:48.200 T:754      info <general>: VideoPlayer: finished waiting
2024-02-12 11:06:48.320 T:791      info <general>: PVR Manager: Cleaned up 0 cached images.
```

Does it mean that the original problem is fixed and something else is wrong? Maybe it needs some configuration? 
Should I close the issue?

**Comment by MoojMidge** [comment]
It looks like you have the `Use YouTube website URLs` option enabled

**Comment by AlexNk** [comment]
> It looks like you have the `Use YouTube website URLs` option enabled

No. I am aware of this issue, so I specially checked that it is disabled and double-checked after updating the module.

**Comment by MoojMidge** [comment]
I'm out of guesses. 

The plugin does not use urls in the form that is shown in your second log snippet. Not actually sure you are even running the plugin from that snippet. 

The proposed fix will resolve the issue shown in your first log snippet, but if there is another problem you will need to provide a complete debug log.

**Comment by AlexNk** [comment]
OK. As the original error no longer happens I will close this ticket and wait for the next release. Then will either re-open it or create a new one.

**Comment by MoojMidge** [comment]
I'll be honest with you - not providing a full log is a massive waste of time and I'm not going to have much interest in looking into this again without it.

**Comment by AlexNk** [comment]
> I'll be honest with you - not providing a full log is a massive waste of time and I'm not going to have much interest in looking into this again without it.

Noted. My bad. Next time will attach a full debug log.

**Comment by AlexNk** [comment]
The issue became reproducible again on v7.0.4+beta.2 - unofficial

THe full debug log is attached
[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/14736086/kodi.log)

**Comment by MoojMidge** [comment]
You are trying to open Youtube website urls.

Not sure how you are trying to do this, maybe through the JSONRPC or web interface, but the plugin is not even being used.

**Comment by AlexNk** [comment]
I'm sending it from Android app via KORE. So it isn't supposed to work?

**Comment by MoojMidge** [comment]
Isn't this you? https://github.com/xbmc/Kore/issues/966

**Comment by AlexNk** [comment]
> Isn't this you? https://github.com/xbmc/Kore/issues/966

Yes. With SendToKodi it worked more or less stable until the recent updates. To me it's not clear what causes the issue.

**Comment by MoojMidge** [comment]
This was already answered in that linked issue. None of this is related to this plugin, it is not even being asked to run.

SendToKodi doesn't use this plugin, so whatever it is doing has nothing to do with this plugin either, let alone any recent updates of this plugin.

Not sure who is looking after Kore, but what they should probably do is just pass the Youtube url directly to the plugin instead of trying, and failing, to parse it based on a limited number of matching patterns.
```
plugin://plugin.video.youtube/uri2addon?uri=
```

**Comment by AlexNk** [comment]
> SendToKodi doesn't use this plugin, so whatever it is doing has nothing to with any recent updates of this plugin.

I see. Thanks for the explanation. This was probably a coincidence.

**Comment by MoojMidge** [comment]
If you want this to work I would recommend updating your existing Kore issue and identifying the option to use `plugin://plugin.video.youtube/uri2addon/?uri=` directly with the YouTube url rather than having Kore parse the url
