### ISSUE TITLE
Start setup message appears every time

### ISSUE THREAD

**Issue by update-freak** [anxdpanic/plugin.video.youtube#604]
### Context

* Add-on Version: v7.0.3.1
* Kodi Version: Nexus (LibreELEC v11.0.6)
* Kodi GUI Language: german
* Operating System: LibreELEC
* Operating System Language: german

### Expected Behavior

That the setup message to set region and language will only appear one time after installation and not every time I start YouTube.
------

### Current Behavior

The setup message will pop up every time I start the YouTube App
-----

### Steps to Reproduce

1.  Install YouTube
2. Start YouTube
3. Then the setup message appear

------

### Log
If necessary I also can provide a log file

**Comment by MoojMidge** [comment]
A log will be required to figure out what is wrong. Specifically need a full debug log:
https://kodi.wiki/view/Log_file/Easy

**Comment by update-freak** [comment]
here is the log file.
I also recognised that in
v7.0.2.2 there it is the setting German and then Deutschland
v7.0.3.1 there it is the setting Deutsch and then Deutschland
Maybe this could be a root cause for the repeating setup message?

I also found out that when you install the v7.0.2.2 then execute the setup to set language and country and then update to v7.0.3.1 you did not have the problem. This happens only when you do a clean install of the v7.0.3.1

Log is from Windows-Laptop
[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/14405785/kodi.log)

**Comment by MoojMidge** [comment]
Thanks for that. Funnily enough was just discussing a very similar problem, and was saying that I thought it had been fixed (and a related problem was fixed in Kodi v20.3), but here you are proving that it is not quite fully sorted out.

The issue is that when the wizard is run, it toggles the plugin setting that enables the wizard, but in versions after v7.0.2.2 the way that the settings are set has changed. Unfortunately the new method to set settings does not seem to be working properly so the plugin thinks that the wizard is required to run all the time.

This will need to be fixed in Kodi, but I have tried to workaround the problem in https://github.com/MoojMidge/plugin.video.youtube/commit/1f4a4f42257363ba478b9b6d9ffb7630b88b019f

Can you test and see if it resolves the problem?

**Comment by update-freak** [comment]
Yes, sure.
I downloaded the v7.0.3.1 and replaced the two files in your linked commit.
Then I did a clean install of the YouTube App --> I have the issue with repeating setup-messages again, so behaviour was the same (=problem not solved yet)

**Comment by MoojMidge** [comment]
> a related problem was fixed in Kodi v20.3

Oh, now the penny drops... I use Kodi v21 and this problem was indeed fixed, but the fix was never backported to Kodi v20.

I am not sure if there will be a new Kodi v20 point release, but will ask if the fix can be backported, if there will be.

In the meantime have changed the plugin to only use the new settings methods in Kodi v21+ (LibreELEC 12) in https://github.com/MoojMidge/plugin.video.youtube/commit/6e9ffa964d498b45fba3bd1d58756f513f3fedb4

Thanks again for taking the time to perform a clean install and produce the debug log.
